### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by odan** [Nyholm/psr7#113]
There is a small typo in this example code:

```php
$response = (new Psr17Factory())->createReponse('200', 'Hello world');
```

It should be:

```php
$response = (new Psr17Factory())->createResponse(200, 'Hello world');
```

Or even better to emit a real `Hello World` text:

```php
$response = (new Psr17Factory())->createResponse(200);
$response->getBody()->write('Hello World');
(new SapiEmitter())->emit($response);
````

**Comment by Zegnat** [comment]
Thanks for noticing! I have now made a PR (#114) addressing this. Please comment there if you have more ideas for how to clean-up that specific usage example.
