### ISSUE TITLE
Add .github folder to .gitattributes export-ignore

### ISSUE THREAD

**Issue by reedy** [Nyholm/psr7#125]
Can you add the .github folder to .gitattributes export-ignore?

**Comment by Nyholm** [comment]
That sounds like a good idea. 
Would you mind doing a PR?

**Comment by Nyholm** [comment]
We should also add phpstan.neon.dist, right?

**Comment by reedy** [comment]
> We should also add phpstan.neon.dist, right?

Well, it's already there, with a . prefix... So we should just drop the prefix :) https://github.com/Nyholm/psr7/blob/master/.gitattributes#L8

**Comment by Nyholm** [comment]
Yes please.
