### ISSUE TITLE
Response::__toString() should not hide exception

### ISSUE THREAD

**Issue by lyrixx** [Nyholm/psr7#142]
https://github.com/Nyholm/psr7/blob/d38874cbc289d25a309cefd04379e24352ced608/src/Stream.php#L98-L109

I found this because of https://github.com/php-http/client-common/issues/186
In my application, I had a 200 with an empty body :exploding_head: 

IMHO, doing this is wrong as it hides the root cause.

More over, in PHP 7.4 it's allowed to throw exception.
And for PHP 7.3-, it prefer a fatal error than something wrong.

WDYT?

**Comment by nicolas-grekas** [comment]
the catch block should start with this IMHO:
```php
if (\PHP_VERSION_ID >= 70400) {
    throw $e;
}
```

**Comment by Tobion** [comment]
https://github.com/guzzle/psr7/pull/316

**Comment by nicolas-grekas** [comment]
> guzzle/psr7#316

Funny that guzzle/psr7 is not PSR-7 compliant: `trigger_error()` with `E_USER_ERROR` is a control flow break, which is explicitly forbidden by the PSR. By default, PHP stops execution and a userland error handler would likely throw (Symfony's does).

Anyway, fix proposed in #144 for the issue here.

**Comment by Tobion** [comment]
```
if (\PHP_VERSION_ID >= 70400) {
    throw $e;
}
```
Is not PSR-7 compliant either. Not sure why you argue against your own suggestion.

**Comment by nicolas-grekas** [comment]
The psr reads as

> This method MUST NOT raise an exception in order to conform with PHP's string casting operations.

Which to me means we can interpret that throwing is compliant, when it's technically possible. :)

**Comment by Tobion** [comment]
so you argue a trigger error control flow break is not allowed but throwing an exception is when it explicitly says "MUST NOT raise an exception". Very creative ;)

**Comment by odan** [comment]
I think this specific PSR-7 rule is no longer "compatible" with PHP 7.4+

**Comment by nicolas-grekas** [comment]
I should have used "fatal error" instead of "control follow break", that'd be more accurate when mentioning E_USER_ERROR, since that's the default behavior, and what psr7 wants to avoid in the first place.

This role is obsoleted by PHP 7.4 for me also.

**Comment by Nyholm** [comment]
Me and @Tobion argued about this on Guzzle/psr7. I was against it. The fact that guzzle merged it anyways and @nicolas-grekas shows me a very liberal interpretation of that PSR7 line of definition, I guess I have to say that I was wrong in https://github.com/guzzle/psr7/issues/271

Im happy to merge a fix for this.

**Comment by nicolas-grekas** [comment]
The PR I don't get at all and looks wrong to me is https://github.com/guzzle/psr7/pull/243, but https://github.com/guzzle/psr7/pull/271 is fine as it fixes a very WTF situation that was justified by argument that are obsoleted by PHP 7.4.

**Comment by nicolas-grekas** [comment]
Note that it would be useful to port #144 to Guzzle if anyone is up to it.
