### ISSUE TITLE
Return value of Nyholm\Psr7\Stream::read() must be of the type string, bool returned

### ISSUE THREAD

**Issue by casahugo** [Nyholm/psr7#153]
In `Nyholm\Psr7\Stream`, the method `read` must return only string but `fread` can be return a boolean
The StreamInterface does not force return type
```php
    public function read($length): string
    {
        if (!$this->readable) {
            throw new \RuntimeException('Cannot read from non-readable stream');
        }

        return \fread($this->stream, $length);
    }
```

**Comment by Zegnat** [comment]
Woops, silly mistake, well spotted!

Not sure exactly when it would return `false`. If we previously established the stream to be readable (as it passes the `if`) but no longer is readable, maybe? Trying to think how we could make a test case for this one.

**Comment by Zegnat** [comment]
Fix is just a clone of how we handle this for `fwrite`:

```diff
diff --git a/src/Stream.php b/src/Stream.php
index 0dd8a2b..2b62e1c 100644
--- a/src/Stream.php
+++ b/src/Stream.php
@@ -240,7 +240,11 @@ final class Stream implements StreamInterface
             throw new \RuntimeException('Cannot read from non-readable stream');
         }
 
-        return \fread($this->stream, $length);
+        if (false === $result = \fread($this->stream, $length)) {
+            throw new \RuntimeException('Unable to read from stream');
+        }
+
+        return $result;
     }
 
     public function getContents(): string
```

Which, I just realised, I am not sure we have tests for either. And it may be impossible to test for. Sounds like something substantial in the PHP/C level needs to go wrong for this to occur?

**Comment by mahagr** [comment]
Maybe you should try to read negative amount of bytes?

**Comment by casahugo** [comment]
Thank you very much for your response
I arrived at the same conclusions, the test seems difficult to write but I may have a track by deleting the resource during reading

**Comment by mahagr** [comment]
Deleting the file doesn't work as unix filesystems keeps the inode reserved/open as long as you have handle on it. I actually have used it to my benefit -- until I noticed that it fails in Windows :(

**Comment by Zegnat** [comment]
Let us bring the discussion about the actual test code into the open PR. Thanks for the quick PR, @casahugo! Keeping the bug open until we bring the PR to a conclusion.
