### ISSUE TITLE
Make Request class non-final?

### ISSUE THREAD

**Issue by pkly** [Nyholm/psr7#163]
Hi, first off, great job, the library is great, love it.
One question though - why is the Request class final? The guzzle implementation isn't final and I see very little reason this one should be...
Is there an actual reason for it or was it just a choice you've made? 
I'm using this library to create a compatible request via the interface but now instead of just doing `new WhateverRequest($data)` I have to do basically `(new WhateverRequest($data))->getRequest()` or `WhateverRequest::create($data)` to achieve the same effect.

**Comment by yethee** [comment]
> Is there an actual reason for it or was it just a choice you've made?

See for details #31, #139
