### ISSUE TITLE
feature request for a non-buffered stream (NonBufferedStream)

### ISSUE THREAD

**Issue by manueldimmler** [Nyholm/psr7#201]
At the moment, it's not possible to use [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) with this implementation.

When calling StreamInterface::write, the content should be echoed and flushed immediately. In addition, the header would have to be emitted immediately in the Response class if the NonBufferedStream is used as the body.

Possible implementation of StreamInterface::write in a new NonBufferedStream class
```php
    public function write($string): int
    {
        $buffered = '';
        while (0 < \ob_get_level()) {
            $buffered = \ob_get_clean() . $buffered;
        }

        echo $buffered . $string;

        \flush();

        return \strlen($string) + \strlen($buffered);
    }
```

Additional lines needed in [MessageTrait::withHeader](https://github.com/Nyholm/psr7/blob/master/src/MessageTrait.php#L76)
```php
        if ($this->stream instanceof NonBufferedStream) {
            header($normalized . ': ' . \implode(', ', $value));
        }
```

**Comment by Nyholm** [comment]
Hm.. I dont really understand. Why would you hold the full response in memory? How would that help you with the article you linked? 

Also, what is the issue using the normal Stream?

**Comment by zonuexe** [comment]
@manueldimmler 
What about Laminas' [`SapiStreamEmitter.php`](https://github.com/laminas/laminas-httphandlerrunner/blob/2.2.x/src/Emitter/SapiStreamEmitter.php)?

**Comment by nicolas-grekas** [comment]
Closing as stalled.
