### ISSUE TITLE
Filter Uri->withUserInfo() input

### ISSUE THREAD

**Issue by mabar** [Nyholm/psr7#206]
I have a login, which contains `@` in username and password. User info with this character is currently not encoded. I think there should be a `filterUserInfo()` method to correctly encode input as other with* methods do.

I checked other popular implementations and all of them do that:
- https://github.com/guzzle/psr7/blob/67c26b443f348a51926030c83481b85718457d3d/src/Uri.php#L436-L439
- https://github.com/slimphp/Slim-Psr7/blob/7e7e63e3b624ed07bde14fbd9f91ab8904402375/src/Uri.php#L174-L177
- https://github.com/laminas/laminas-diactoros/blob/6028af6c3b5ced4d063a680d2483cce67578b902/src/Uri.php#L275-L278

Most accurate seem to be guzzle and laminas implementations which do this:

```php
    private function filterUserInfo($userInfo): string
    {
        if (!is_string($userInfo)) {
            throw new \InvalidArgumentException('User info must be a string');
        }

        return preg_replace_callback(
            '/(?:[^%' . self::CHAR_UNRESERVED . self::CHAR_SUB_DELIMS . ']+|%(?![A-Fa-f0-9]{2}))/',
            [$this, 'rawurlencodeMatchZero'],
            $userInfo
        );
    }
```

Only difference is in laminas/laminas-diactoros which also checks for invalid UTF-8 characters

**Comment by boesing** [comment]
Hey there, 

thanks to `http-plug/discovery`, I stumbled over this issue as well. We are unable to connect to our elasticsearch anymore as some 3rd-party dependency depends on this package which has a higher priority in that discovery thing.

Is there anything I can do to move this forward?

**Comment by nicolas-grekas** [comment]
It could be worth contributing this case to https://github.com/php-http/psr7-integration-tests
Could you give it a try maybe @boesing or @mabar ?
