### ISSUE TITLE
Response::__toString()

### ISSUE THREAD

**Issue by vanodevium** [Nyholm/psr7#209]
Is there any chance to stringify response object to string like `\GuzzleHttp\Psr7\Message::toString()` can do this.

Example of stringified response:
```
HTTP/1.1 200 OK
Content-Length: 9
Content-Type: application/json
Connection: keep-alive

{"boo":1}
```

This functionality is really important for TCP connections.

I would be grateful for any help.

**Comment by boesing** [comment]
Maybe this can be of help:
https://github.com/laminas/laminas-httphandlerrunner/tree/2.6.x/src/Emitter


Its can handle any PSR-7 `ResponseInterface` and does exactly what you need.

**Comment by nicolas-grekas** [comment]
This lib provides only PSR-7 methods.
