### ISSUE TITLE
"Site not found" for https://tnyholm.se 

### ISSUE THREAD

**Issue by florisluiten** [Nyholm/psr7#238]
Hi,

In the composer.json the website is listed as "https://tnyholm.se", however, that page throws an "Site not found" error.  Perhaps update the website to https://github.com/Nyholm/psr7?

**Comment by Nyholm** [comment]
Yeah. It is a github hosted page. But a few weeks ago decided to Github remove that page.. Not sure why.

**Comment by Nyholm** [comment]
I just did a new push and it was rebuild. Now it is up and running. 

Thank you for the reminder.
