### ISSUE TITLE
psr/http-message 版本问题

### ISSUE THREAD

**Issue by chen900804** [Nyholm/psr7#239]
psr/http-message  Hope to support 2.0

**Comment by Nyholm** [comment]
We just merged https://github.com/Nyholm/psr7/pull/234

I would be happy if you tried it out in your project before we release it.

**Comment by chen900804** [comment]
I hope to release a new version as soon as possible. I don't want to downgrade to 1.0 in my project

**Comment by Nyholm** [comment]
Try installing `composer req nyholm/psr7:1.7.x-dev`

If that works in your project than I would be more comfortable to release.

**Comment by Nyholm** [comment]
I tested this in a few of my applications. It worked perfectly. 

I release 1.7.0. See https://github.com/Nyholm/psr7/releases/tag/1.7.0
