### ISSUE TITLE
Review UploadedFile and ServerRequest

### ISSUE THREAD

**Issue by Nyholm** [Nyholm/psr7#3]
See if we can remove features and add type hints

**Comment by Zegnat** [comment]
Now that there are factories available, would it be acceptable to clean-up ServerRequest by moving `fromGlobals` and `getUriFromGlobals` to ServerRequestFactory and UriFactory respectively? This means ServerRequest can only be instantiated by `__construct` or through the factory, which makes sense to me.

If moving `getUriFromGlobals` to UriFactory is acceptable I would propose a slightly different signature:

```php
public function createUriFromArray(array $server)
```

This would mirror ServerRequestFactory’s `createServerRequestFromArray` and gets rid of the hard dependency on a global `$_SERVER`. That in turn would allow us to get rid of the `$SERVER = $_SERVER`, `$_SERVER = $server` jumble.

This only leaves `normalizeFiles` on the ServerRequest as a bit of an odd-one out, but I haven’t really looked into UploadedFile yet.

Let me know if a PR for the above would be welcome.

**Comment by Nyholm** [comment]
Great. Lets move away from $_GLOBALS. 
I would be happy to review a PR.
