### ISSUE TITLE
protected class variables ?

### ISSUE THREAD

**Issue by ncou** [Nyholm/psr7#39]
Do you think some class variables like "private headers[]" or "private statusCode" actually marked as private, will be changed as protected ?

I will try to extend you Response classe to add some helpers, so a direct acces to the variables could make the dev more smooth. 

What are your opinion on this subject ? 

PS : After looking at guzzle and diactoros implementation, the first lib stick to private variables, the second is a mix with private+protected.

**Comment by Zegnat** [comment]
There is an entire discussion about marking the classes in this project as final, see #31. If that goes through, extending Response will not be possible at all. Maybe get in on that discussion?

**Comment by ncou** [comment]
Thanks i will read this discussion.
