### ISSUE TITLE
enforce header value as string ?

### ISSUE THREAD

**Issue by ncou** [Nyholm/psr7#40]
Hi,

Shouldn't we cast the header value as string in the trimHeaderValues() function ? 

A few http headers represent a number of seconds or bytes, and the user could easily does something like this : 
`new Response(200, ['Age' => 60]);`

instead of using a string for the value. In this case the trimHeaderValues() will crash trying to da a trim on a non string.

It seems more logical to cast the value as string before trying to do the trim, no ? or perhaps doesn't apply the trim if the value is not a string ? or just let it crash ?

what is you opinion ?

**Comment by Zegnat** [comment]
I wouldn’t mind throwing an exception for non-string values, the same way we do in `withHeader`:

https://github.com/Nyholm/psr7/blob/b6b62a428f6a49e2b5e8bef9e112b0608abc4b35/src/MessageTrait.php#L87-L91

In essence I guess this is what is happening now, when the anonymous function within `trimHeaderValues` throws a TypeError. But it may be better if we throw it ourselves?

Did you prefer any specific option, @ncou?

**Comment by ncou** [comment]
yes it may be better to throw it ourself, the controls are already presents in the withHeader and withAddedHeader so the controls should also be applyed on the setHeaders(), IMHO.

perhaps you could try to add a new function to do the checks, somthing like : "assertHeaderValues(string $header, array $values)" and this function could do the following asserts/verifications :

```php
       if (empty($values)) {
            throw new \InvalidArgumentException('Header values must be non-empty strings');
        }
        if (!is_string($header) || empty($header)) {
            throw new \InvalidArgumentException('Header name must be non-empty strings');
        }
        foreach ( array_values($values) as $value) {
            if (!is_string($value)) {
                throw new \InvalidArgumentException('Header values must be non-empty strings');
            }
        }
```
and you keep the convertion from string to array for the value variable before calling this assert method. and after you call the trimHeaderValues. This new function could be used/called in setHeaders() / withHeader() and withAddedHeader() and avoid some duplication code.

What do you think ?

**Comment by ncou** [comment]
@Zegnat : so what is your opinion ?

**Comment by Zegnat** [comment]
I do think we should use the same exception throwing in those 3 methods, for sure.

I am ambivalent on creating an extra private method for it. It is good DRY to abstract it. On the other hand, I like it when I am looking at an exception and it originates from the method I called rather than having to go further up in the stack trace. But that is a personal quirk.

**Comment by ncou** [comment]
@Nyholm : and your opinion ?

**Comment by ncou** [comment]
no news ?

**Comment by Nyholm** [comment]
When I closer inspected this. We use the same validation 3(!) times. I used a separate function. See #48

**Comment by Nyholm** [comment]
Wohoo. This is all fixed now.
