### ISSUE TITLE
ServerRequest::getBody method returns an empty stream

### ISSUE THREAD

**Issue by xaben** [Nyholm/psr7#42]
ServerRequest::getBody method returns an empty stream, while running `file_get_contents("php://input")` actually returns the correct POST body. I cannot find anywhere how the body resource is set.

The related place is: https://github.com/Nyholm/psr7/blob/master/src/MessageTrait.php#L160

Suppose we need to read the raw input here?

**Comment by Zegnat** [comment]
The body is usually set around the creation of the `ServerRequest` instance, so this will depend on how you are instantiating.

It doesn’t look like [the current `ServerRequestFactory`](https://github.com/Nyholm/psr7/blob/484aa5f77c5439acff308392091c90ee5319ce3d/src/Factory/ServerRequestFactory.php) has any method that will automatically assign a body. The [current PSR-17 draft Interface](https://github.com/http-interop/http-factory/blob/c8d8491117c4ecc080b5d80e380f5aa590232fcb/src/ServerRequestFactoryInterface.php) does not add any method that does this either, so I do not see any priority for us to add it here.

Building a `ServerRequest` object from an actual web server request is going to be up to your framework.

Another option is to add the body post-creation of the object. Something like this (note: untested):

```php
// Assuming $request is an instance of ServerRequest
$body = (new \Nyholm\Psr7\Factory\StreamFactory())
    ->createStreamFromFile('php://input');
$request = $request->withBody($body);

**Comment by xaben** [comment]
Ok, thank you for the explanation. I was expecting it would be set by `ServerRequestFactory::createServerRequestFromGlobals` method though, and it was unexpected to not have one.

**Comment by Zegnat** [comment]
I can imagine how that might be a little unexpected! Happy to have explained it, and I will close this issue as resolved.

I have opened 2 new issues:

1. #43 about getting rid of the `createServerRequestFromGlobals` method (and several others) so people are less likely to make this mistake. PSR-17 has dropped these too.
2. #44 about introducing a separate helper class that could be used to create fully filled `ServerRequest` instances.

Feel free to leave a comment on either of those if you have any further thoughts!

**Comment by Zegnat** [comment]
@xaben in case you didn’t subscribe to the other issues: there is [a new package (nyholm/psr7-server)](https://github.com/Nyholm/psr7-server) that is able to create a `ServerRequest` using any PSR-17 implementation.

See [the README of the latest v1 release](https://github.com/Nyholm/psr7/blob/1.0.0/README.md#create-server-requests) for an example!
