### ISSUE TITLE
Separate class specifically for building ServerRequest instance of the current HTTP request.

### ISSUE THREAD

**Issue by Zegnat** [Nyholm/psr7#44]
As I documented in #43, there isn’t an automatic way (defined by PSR-17) to take the current HTTP request as seen by PHP (combination of superglobals, `php://input`, etc.) and make it a `ServerRequest` instance. This is by design.

I’d propose building a separate helper class following [an idea initially mentioned on the PSR-17 repo](https://github.com/http-interop/http-factory/issues/31#issuecomment-300560775):

``` php
use ServerRequestCreator\Creator;

$creator = new Creator(new PsrServerRequestFactory());

$serverRequest = $creator->fromGlobals([
    'useMethodOverride' => true,
    'useIISRewriteModule' => true
]);
```

I am not so sure about the options array used there, or even the names, but it would make sense to me to offer this as part of the package. Simply because people expect it. Maybe something akin to:

``` php
use Nyholm\Psr7\Factory\ServerRequestFactory;
use Nyholm\Psr7\Factory\StreamFactory;
use Nyholm\Psr7\Helper\ServerRequestCreator;

$creator = new ServerRequestCreator(
    new ServerRequestFactory(),
    new StreamFactory()
);

$serverRequest = $creator->fromGlobals();
```

**Comment by Nyholm** [comment]
At the moment, our server request factory supports creating a request from super globals. But Im +1 for the changes you suggest. I would be happy to review such PR.

**Comment by Zegnat** [comment]
I am currently on holiday – which is why my reviews have been left hanging – but I’ll have a go at a PR for this next week!

**Comment by Nyholm** [comment]
While writing docs I felt some inspiration for this issue. I decided to keep this package "super pure" so all extra features has to go somewhere else. =) 

I've added nyholm/psr7-server with this feature. It was basically just to move code. See #55. 

(I hope you do not mind)

**Comment by Zegnat** [comment]
Pulling it to a separate package is even better than just to a separate class, IMO. So I definitely do not mind.
