### ISSUE TITLE
Improve compatibility with PHP 7.2

### ISSUE THREAD

**Issue by ninsuo** [Nyholm/psr7#45]
Hey there,

FYI, php enforce type hinting on a few native functions from 7.2. Thus, it is required to cast before sending values.

I've just got that exception when upgrading PHP today, as this project is a guzzle dependency.

Have a great day,
Alain

![screen shot 2018-06-24 at 21 04 14](https://user-images.githubusercontent.com/4152132/41822585-4e7bb7b6-77f2-11e8-8932-375f602733f0.png)

**Comment by Zegnat** [comment]
Related to #40, which is about making sure we only accept strings there.

**Comment by Nyholm** [comment]
This is fixed by #34
