### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rilwis** [Nyholm/psr7#53]
I really like this library as it's small and fast. While it's not popular as Zend Diactoros or Guzzle, it strictly follows the PSR standards, which I really appreciate.

However, one thing that makes me wondering from use it or not is the documentation. There's *nothing*, even a "hello world" example. Other libraries do have. So, I'd suggest adding some basic usage in the README to let developers how to use it.

Thanks

**Comment by Nyholm** [comment]
That is a great idea. Thank you. 

Could you give me 4-5 "questions" that you would like the documentation to answer?

**Comment by rilwis** [comment]
No problem. I think these are the most basic things:

- Installation
- Getting Started / Basic Usage
- Public methods for each objects (perhaps this repeats from PSR, but still worth mentioning)
- Integration with your app/framework
