### ISSUE TITLE
Scope all constants to root, or not?

### ISSUE THREAD

**Issue by Zegnat** [Nyholm/psr7#71]
When I was checking `\` prefixes for #67 I saw the factory uses `\UPLOAD_ERR_OK`:

https://github.com/Nyholm/psr7/blob/36870acbf2ef440db6a072509afc92f5d4155d77/src/Factory/Psr17Factory.php#L41

Every other time constants are used, we seem to leave it up to PHP to figure out we want them from outside our own namespace. Here is `UPLOAD_ERR_OK`:

https://github.com/Nyholm/psr7/blob/90807bc10796287265f726e942bcbb2272fbc5b6/src/UploadedFile.php#L137

Is there some way to make StyleCI check this? Is it even important?

**Comment by Nyholm** [comment]
Yes. Lets do `\` before each constant. 

FYI: https://github.com/php-fig/http-factory/issues/3
