### ISSUE TITLE
Make serialisable?

### ISSUE THREAD

**Issue by Zegnat** [Nyholm/psr7#81]
Is it an idea to make all of the final objects implement [`Serializable`](https://secure.php.net/manual/en/class.serializable.php)?

One use-case is for HTTP caches to store request/response objects easily. I ran into this [today](https://github.com/Zegnat/php-webmention-endpoint-discovery/commit/b833c56682fc959c0a2ddd52920020f36f1a3697) and ended up requiring [zend-diactoros](https://zendframework.github.io/zend-diactoros/) for [its Serialization](https://zendframework.github.io/zend-diactoros/serialization/), which just means I end up with two entire PSR-7 implementations loaded at the same time. Any unserialised Nyholm object becomes a Zend object.

The drawback being that we would be adding methods that aren’t specifically defined by PSR-7.

Alternatively this could be spun of just like [psr7-server](https://github.com/Nyholm/psr7-server). Which I might work on any way. But did want to throw this up for discussion in the mean time.

**Comment by Nyholm** [comment]
Hm. I've got this problem as well in the php-http/cache-plugin. See [here](https://github.com/php-http/cache-plugin/blob/master/src/CachePlugin.php#L197-L206) and [here](https://github.com/php-http/cache-plugin/blob/master/src/CachePlugin.php#L395-L412).

Yeah, lets try to see how an implementation would look. You would of course have problem to serialize the Stream.

**Comment by nicolas-grekas** [comment]
If anyone is willing to work on this, please don't implement `Serializable`, it's a trap. Implement either `__sleep()/__wakeup()` or `__serialize()/__unserialize()`.

**Comment by nicolas-grekas** [comment]
As I put in #207, this is not explicitly allowed by PSR-7, so doing that would enable building on a non-specified behavior, enabling tight-coupling to one specific implementation.

Instead, I'd advise not serializing PSR-7 objects directly.

An alternative course of action might be to add a test case to [php-http/psr7-integration-tests](https://github.com/php-http/psr7-integration-tests/) and ensure that all major implementations agree on this behavior. That'd create a sort of de facto standard.

Please let us know if this happens.
Closing meanwhile.

**Comment by nicolas-grekas** [comment]
Side note: if you call `detach()` on the body Stream object clears the internal resource stream. This might be portable.
See https://github.com/php-http/cache-plugin/pull/82 for how caching can leverage this at a generic level.
