### ISSUE TITLE
Header values must be non-empty strings

### ISSUE THREAD

**Issue by TiMESPLiNTER** [Nyholm/psr7#82]
If I request a file from AWS I get an empty header:

```
x-amz-id-2: mhBUIOWKJ*()Z=*U?IPZJ))(J=OetWk=
x-amz-meta-orientation:
x-amz-request-id: 1ZUWIODKLD
```

which leads to an exception: 

```php
throw new \InvalidArgumentException('Header values must be non-empty strings');
```

in the `MessageTrait`. So I have no chance to use this library with servers who may return an empty header in their response.

Why is this psr7 implementation so strict with this? Can we change the behavior? Like for example just ignore empty headers and not throw an exception?

**Comment by Nyholm** [comment]
According to [RFC-7230](https://tools.ietf.org/html/rfc7230#section-3.2) require header-value to be at least 1 character long. Or am I mistaken?

**Comment by Zegnat** [comment]
This looks like we made a mistake, thanks for spotting it!

As discussed in #38, empty headers are very much allowed. But then in #48 this was undone. Oops!

Well spotted. I’ll add a test to the test suite so it (hopefully) wont happen again.

**Comment by Zegnat** [comment]
@Nyholm, sorry, looks like you were commenting at the same time as me :wink: You are mistaken, you can check the ABNF in the comment block included above our code: the field-value starts with a `*` and is optional.

**Comment by Nyholm** [comment]
Okey. Thank you. That should be fixed then. 
Could @TiMESPLiNTER submit a PR?

**Comment by TiMESPLiNTER** [comment]
I would just remove the excpetions for empty headers then and write a test case for it?

**Comment by Zegnat** [comment]
Uuhm. I just wrote the following test and it passes:

```php
    public function testCanHaveHeaderWithEmptyValue()
    {
        $r = new Request('GET', 'https://example.com/');
        $r = $r->withHeader('Foo', '');
        $this->assertEquals('', $r->getHeaderLine('Foo'));
    }
```

Are you sure you are using the latest version of the library?

**Comment by TiMESPLiNTER** [comment]
Oops, sorry! I use https://github.com/kriswallsmith/Buzz which still uses `0.3`. I'll do a PR over there to update the dependency.

I leave this Issue open as you may want to attach your testcase to it?

**Comment by TiMESPLiNTER** [comment]
Ah I just saw you already commited that to Buzz and it's in master. So let's hope we will get a new release soon.

**Comment by Zegnat** [comment]
I’ll PR tests for empty header name and empty header value in a minute.

@Nyholm is this worth PR’ing to the integration tests instead? In [`\Psr\Http\Message\MessageInterface\MessageTrait::testWithHeaderInvalidArguments`](https://github.com/php-http/psr7-integration-tests/blob/master/src/MessageTrait.php#L111-L135) it seems to cover the empty header name (which is not allowed), but I don’t see it cover empty header values anywhere?
