### ISSUE TITLE
ServerRequest fails to initialize with empty body

### ISSUE THREAD

**Issue by mindplay-dk** [Nyholm/psr7#94]
The `ServerRequest` constructor ([deliberately](https://github.com/Nyholm/psr7/blob/master/src/ServerRequest.php#L62)?) fails to initialize with an empty body:

```php
        if ('' !== $body && null !== $body) {
            $this->stream = Stream::create($body);
        }
```

Why the `'' !== $body` condition?

I can understand defaulting to `null` meaning "no body". (even though I'm unsure as to the point of partially initializing a Response instance that violates it's own internal constraints, but...)

If I explicitly specify the empty string `""` as the body, why wouldn't you initialize with an empty stream?

It's inconsistent with the [Stream constructor](https://github.com/Nyholm/psr7/blob/master/src/Stream.php#L63), which explicitly permits the empty string *and* defaults to it.

Having to explicitly initialize every created `ServerRequest` instance with `Stream::create()` or `StreamFactoryInterface` is a bit impractical (especially in test-suites) and creates unnecessary coupling.

Can we remove this condition, please?

**Comment by Zegnat** [comment]
For empty and `null` bodies the creation of the `Stream` object is [delayed until `getBody()` is called](https://github.com/Nyholm/psr7/blob/867ce43052cb60e32001a8a0aa825f1830882ad8/src/MessageTrait.php#L117-L124). This is an implementation detail and I am not sure it needs changing. (And might be giving us a small performance boost if we never end up creating the `Stream`? Not sure.)

> Having to explicitly initialize every created `ServerRequest` instance with `Stream::create()` or `StreamFactoryInterface` is a bit impractical (especially in test-suites) and creates unnecessary coupling.

Where did you get the idea you would need to do this? The docblock [clearly specifies](https://github.com/Nyholm/psr7/blob/867ce43052cb60e32001a8a0aa825f1830882ad8/src/ServerRequest.php#L41) that passing a string or `null` for `$body` is allowed.

**Comment by mindplay-dk** [comment]
> Where did you get the idea you would need to do this?

I was reading the conditional initialization code [here](https://github.com/Nyholm/psr7/blob/867ce43052cb60e32001a8a0aa825f1830882ad8/src/ServerRequest.php#L62-L64), which makes it appear as though it doesn't initialize at all.

I now see that it [defers](https://github.com/Nyholm/psr7/blob/master/src/MessageTrait.php#L119-L121) the initialization of empty streams - this wasn't obvious, for two reasons:

1. because it's [type-hinted](https://github.com/Nyholm/psr7/blob/master/src/MessageTrait.php#L29) incorrectly - it should have an `|null` suffix in the type-hint. (the missing initialization seems like an error because it's violating an invariant.)

2. there's nothing in the doc-block that explains that passing a `null` body actually *means*.

Probably both should be addressed?

**Comment by mindplay-dk** [comment]
To be clear, I'm happy with the way it works :-)

**Comment by Zegnat** [comment]
> 1. because it’s [type-hinted](https://github.com/Nyholm/psr7/blob/867ce43052cb60e32001a8a0aa825f1830882ad8/src/MessageTrait.php#L29) incorrectly – it should have an `|null` suffix in the type-hint.

As I do not use an IDE that uses those property type-hints this never occurred to me! That should definitely be corrected.

Though basing it off of the Response and Request constructors might lead to weird edge-cases. Changing it to `string|null|StreamInterface` (i.e. just dropping `resource`) might be overstating things, as only empty strings are handled as a value 🤔 

> 2. there’s nothing in the doc-block that explains what passing a `null` body actually _means_.

I feel like this too should be addressed, but may even be an issue on its own? Feels somewhat more documentation related.

I’ll see if I can’t free up some time this afternoon to get a PR started!
