### ISSUE TITLE
Response: Non-standard HTTP status codes cannot be used

### ISSUE THREAD

**Issue by mahagr** [Nyholm/psr7#95]
Right now the implementation prevents me from using unofficial HTTP status codes, like Laravels 419 Page Expired.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

I think those should be allowed if the `$reason` parameter in the constructor is set.

**Comment by Zegnat** [comment]
Where are you seeing this problem? I can’t reproduce it.

I wrote the following test case, and it passes without any issues, so I can correctly define any custom (non-standard) HTTP status codes and reasons:

```php
    public function testLaravelCustomStatus()
    {
        $first = new Response(419, [], null, '1.1', 'Page Expired');
        $second = new Response(419);

        $this->assertSame(419, $first->getStatusCode());
        $this->assertSame(419, $second->getStatusCode());
        $this->assertSame('Page Expired', $first->getReasonPhrase());
        $this->assertSame('', $second->getReasonPhrase());
    }
```

Both objects hold the `419` status code, and do not prevent me from creating them in any way. The first keeps the expected reason phrase, while the second one correctly doesn’t have any as none has been defined as default for `419`.

**Comment by Nyholm** [comment]
As far as I know, you can use any status code. Even 677 is allowed. Could you help to reproduce this? 

Btw. You have to use an integer. The string “417” is not good.

**Comment by mahagr** [comment]
Sorry about the delay. I will try to find some time in order to give example code.
